spring.application.name=event.ticketing.fraud.control.resetful.api


# __SECRET__
application.security.jwt.secret-key=__256_BIT__

# __REFRESH_TOKEN_KEY__
application.security.jwt.refresh-token-prefix=auth:refresh_token:

# __TOKEN_EXPIRY__
application.security.jwt.refresh-token.expiration-second=604800
application.security.jwt.access-token.expiration-second=900