spring.application.name=event.ticketing.fraud.control.resetful.api
server.port=5000
spring.datasource.url=jdbc:postgresql://localhost:5432/event.ticketing.system.db?currentSchema=identity_security,ticketing_schema,public
spring.datasource.username=postgres
spring.datasource.password=__YOUR_DB_PASSWORD__

# Hibernate config
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.orm.jdbc.bind=TRACE
logging.level.org.springframework.orm.jpa=DEBUG
logging.level.org.springframework.transaction=DEBUG

# Corrected Dialect
spring.session.jdbc.initialize-schema=always
spring.session.store-type=jdbc
spring.session.jdbc.platform=postgresql


# __SECRET__
application.security.jwt.secret-key=GN5H6OtoExY8lronWr2Y2eqXkgDuBXS8jiWF8UbZG61iCVQkdEnPQgGR83YOVlYs

# __REFRESH_TOKEN_KEY__
application.security.redis.refresh-token-prefix=auth:refresh_token:

# __TOKEN_EXPIRY__
application.security.jwt.refresh-token.expiration-second=604800
application.security.jwt.access-token.expiration-second=900

# __REDIS__
application.security.redis.lock.event-prefix=lock:event
